### ISSUE TITLE
Resize indent within selection only if selection exists?

### ISSUE THREAD

**Issue by caleb531** [gfpacheco/atom-resize-indent#1]
Hi,

First of all, let me just say that this is a great package. I don't _always_ need to use it, but when I do, it's quite handy.

However, it seems to me that the _resize indent_ commands apply to the entire document. This is fine as a default, though I would also prefer—if I have something selected—that the resize only applies to the text within the selection.

Could this feature be added?

Thanks,
Caleb

**Comment by gfpacheco** [comment]
Better late than never:

Implemented on https://github.com/gfpacheco/atom-resize-indent/commit/b9206c0ca2702b08762cd86ddab1907e39957a26 and relased on [v0.3.0](https://github.com/gfpacheco/atom-resize-indent/releases/tag/v0.3.0)
