### ISSUE TITLE
Add more options to the menu

### ISSUE THREAD

**Issue by ghedsouza** [gfpacheco/atom-resize-indent#2]
The application menu (https://github.com/gfpacheco/atom-resize-indent/blob/master/menus/application-menu.cson) has only one option right now.
- Could we add a "Half-size" option?
- Could we add some quick options to let you directly specify common indentation levels. I'm thinking of going with options from 1-8 spaces (a la Sublime Text).

I'm willing to submit a PR for this myself, if the change is okayed. cc @gfpacheco

**Comment by gfpacheco** [comment]
The first suggestion is sure welcome!

About the second one, I'm just not sure how it would be implemented, since currently we don't have the space count by tab, making it hard to specify the new one.

If you submit the second PR separately we can discuss it.
